### ISSUE TITLE
"Starting Communications with Meter Failed" w/ Calibrite Colorchecker Display Plus

### ISSUE THREAD

**Issue by KyleLehtinenDev** [arthur-liberman/hcfr-code#5]
OS: Windows 11
Meter: Calibrite Colorchecker Display Plus
Driver: Default Windows

I have a new colorimeter which is detected and works correctly with the Calibrite Profiler software, but in HCFR when creating a new project I get a "Starting communications with meter failed" error. The meter is not visible in the meter selection drop down.

I briefly looked into getting up and running with ArgyllCMS driver, however I didn't proceed once I found [on the HCFR Wiki](https://sourceforge.net/p/hcfr/wiki/i1%20Display%203%20%26%20colormunki%20display/) that the Colormunki meters (which I understand this line of Colorimeter to be derived from) should be supported with the standard Windows Driver. I also didn't find a lot exploring this issue with this particular meter.

**Comment by nicko88** [comment]
I am not sure what it causing your issue, but I just want to say that I have used that exact meter with HCFR and it worked just fine for me with no driver.  Just the standard Windows HID driver.  So I just wanted to say that it should be working.

Maybe you installed some Calibrate driver and need to remove that?  How does your meter show up in your device manager?

**Comment by KyleLehtinenDev** [comment]
Thanks for the fast response!

It shows up as "HID-Compliant vendor-defined device", I had to unplug a few other USB devices and look at each device event log to identify it though, there's no wording to identify it as a Calibrite Colorchecker or such.

I uninstalled the HCFR and the Calibrite Profiler (which does work with the meter), and reinstalled the latest release of HCFR, but I still get that error.

**Comment by KyleLehtinenDev** [comment]
Good news! I fixed this by uninstalling the Calibrite Profiler and re-installing the Windows driver under Device Manager. After a reboot the sensor was seen and reported by HCFR!

**Comment by KyleLehtinenDev** [comment]
Little more detail on this, Alienware Control Center's Service turned out to be causing this issue. When I rebooted I would get sensor access briefly before the AWCC service spun up, then the error would return. After manually stopping AWCC in Windows Services the sensor was able to connect successfully repeatedly.
